### ISSUE TITLE
*~ FAQs ~*

### ISSUE THREAD

**Issue by amandaharlin** [techlahoma/techlahoma_lander#12]
what does everyone think about having an faq section? we need questions to answer too though, so lmk what you've answered or have asked about techlahoma or the tech scene in oklahoma.

**Comment by amandaharlin** [comment]
some questions we might consider answering:

* what is techlahoma?
* how do i get involved in the tech scene in oklahoma?
* how do i start a new user group?
* i want to teach a workshop on a tech topic. how do i arrange that?
* i want to start programming but don't know where to begin
* tech degrees in oklahoma? 4 year vs 2 year schools?
* where to look for tech jobs in oklahoma?

**Comment by jagthedrummer** [comment]
👍 on a faq

**Comment by the-simian** [comment]
I added a FAQ, but we still need to complete some questions. Since its in the site, but unlinked I"ll close this
