### ISSUE TITLE
Provide link to press articles

### ISSUE THREAD

**Issue by energydev** [techlahoma/techlahoma_lander#22]
Provide a link to a location that links to press articles like the one in 405 magazine.

**Comment by jagthedrummer** [comment]
Does anyone have a link to that article?

**Comment by the-simian** [comment]
hey, I'm gonna close this because I've added a page, and we can make it live whenever we want

you can see here: [http://www.techlahoma.org/test-press](http://www.techlahoma.org/test-press)

**Comment by energydev** [comment]
@the-simian the test-press page looks awesome! Looks ready to go live.
