### ISSUE TITLE
National Events We Sponsor (photo caption correction?)

### ISSUE THREAD

**Issue by energydev** [techlahoma/techlahoma_lander#29]
Under "National Events We Sponsor" on the Events page at http://www.techlahoma.org/events/ there are two photos. Both say they are for SQL Saturday OKC. The one on the left is definitely from SQL Saturday OKC, however, the second one might be for another event. Bringing this up, in case the caption should be changed.

**Comment by amandaharlin** [comment]
thanks! i changed the caption to read 'BSides OK Tulsa'

**Comment by the-simian** [comment]
awesome!
